[package]
name = "devsim"
version = "0.1.0"
authors = ["Gregory Mitrano <gregory.mitrano@gmail.com>"]
edition = "2018"

[dependencies]
gumdrop = "0.8"
goblin = "0.2"
pbr = "1"

[build-dependencies]
cmake = "0.1"
